name: Build APK Fix Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ekstrak File
        run: |
          # Ekstrak file yang kamu upload
          unzip playthedarknes.zip
          
          # Trik untuk mencari pubspec.yaml dan memindahkan isinya ke luar
          # Ini memperbaiki masalah folder di dalam folder
          target=$(find . -name "pubspec.yaml" -printf "%h\n" | head -n 1)
          if [ -n "$target" ]; then
            echo "Ditemukan di: $target"
            cp -r "$target"/* .
          else
            echo "Error: File pubspec.yaml tidak ada di dalam ZIP!"
            exit 1
          fi

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Proses
        run: |
          # Paksa buat ulang struktur android agar fresh
          flutter create . --overwrite
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aplikasi-jadi
          path: build/app/outputs/flutter-apk/app-release.apk
