name: Build APK dengan Assets

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ekstrak File Project
        run: |
          # Ekstrak file yang baru diupload
          unzip project.zip
          
          # Mencari lokasi pubspec.yaml
          target=$(find . -name "pubspec.yaml" -printf "%h\n" | head -n 1)
          
          # Memindahkan semua isi folder project (termasuk assets) ke root
          if [ -n "$target" ]; then
            cp -r "$target"/* .
            echo "Project dan Assets berhasil dipindahkan dari $target"
          fi

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Persiapan Build
        run: |
          # Overwrite agar folder android dibuat otomatis
          flutter create . --overwrite
          flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Download Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-with-assets
          path: build/app/outputs/flutter-apk/app-release.apk
