name: Build APK Sekali Klik

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ekstrak File ZIP Apapun
        run: |
          # Cari file .zip apa aja yang ada di repo
          ZIP_FILE=$(ls *.zip | head -n 1)
          
          if [ -z "$ZIP_FILE" ]; then
            echo "KOK KOSONG? ZIP-nya belum ke-upload beneran itu."
            ls -R
            exit 1
          fi

          echo "Bongkar file: $ZIP_FILE"
          unzip -o "$ZIP_FILE"
          
          # Cari pubspec.yaml dan bawa ke folder utama
          TARGET=$(find . -name "pubspec.yaml" -printf "%h\n" | head -n 1)
          if [ -n "$TARGET" ]; then
            cp -r "$TARGET"/* .
          fi

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Hajarr Build
        run: |
          flutter create . --overwrite
          flutter pub get
          flutter build apk --release

      - name: Ambil APK-nya Dimari
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
