name: Build Vionix Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK Anti Demo
        run: |
          # 1. Bikin struktur pendukung TANPA nyentuh folder lib
          # Kita cuma minta mesin bikin folder android/ yang ilang
          flutter create . --platforms android
          
          # 2. Ambil library
          flutter pub get
          
          # 3. Rakit APK
          flutter build apk --release

      - name: Ambil File APK
        uses: actions/upload-artifact@v4
        with:
          name: VionixEngine-Sukses
          path: build/app/outputs/flutter-apk/app-release.apk
