name: Cek Isi ZIP

on:
  workflow_dispatch:

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ekstrak File
        run: |
          # Membuka file
          unzip playthedarknes.zip
          
          # Menampilkan daftar file yang berhasil diekstrak ke log
          echo "--- DAFTAR FILE SETELAH UNZIP ---"
          ls -R
          
      - name: Simpan Hasil Ekstrak ke Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hasil-ekstrak-zip
          path: .
          # Kita upload semuanya untuk kita cek strukturnya
