name: Build APK Fix Struktur

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK Anti Error
        run: |
          # 1. Paksa bikin kerangka Android tapi JANGAN nimpa folder lib
          # Kita hapus dulu folder android lama kalau ada yang rusak
          rm -rf android
          flutter create . --platforms android
          
          # 2. Ambil library
          flutter pub get
          
          # 3. Rakit APK
          flutter build apk --release

      - name: Ambil File APK
        uses: actions/upload-artifact@v4
        with:
          name: aplikasi-asli-fix
          path: build/app/outputs/flutter-apk/app-release.apk
