name: Build APK Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ekstrak File Apapun
        run: |
          # Perintah ini akan otomatis unzip file .zip apapun yang dia temukan
          unzip *.zip
          
          # Cari pubspec.yaml dan pindahkan isinya ke folder utama
          PUBSPEC_PATH=$(find . -name "pubspec.yaml" -print -quit)
          if [ -n "$PUBSPEC_PATH" ]; then
            PROJECT_ROOT=$(dirname "$PUBSPEC_PATH")
            cp -r "$PROJECT_ROOT"/* .
            echo "Project found in $PROJECT_ROOT"
          else
            echo "Error: pubspec.yaml tidak ada di dalam ZIP!"
            ls -R # Menampilkan daftar file untuk pengecekan jika gagal
            exit 1
          fi

      - uses: subosito/flutter-action@v2
        with:
          channel: '
