name: Build APK Tanpa ZIP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Mengatur lingkungan Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Proses merakit APK
      - name: Build APK
        run: |
          # Perintah ini untuk memperbaiki struktur folder otomatis
          flutter create . --overwrite
          flutter pub get
          flutter build apk --release

      # Mengambil hasil APK untuk didownload
      - name: Download Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: aplikasi-darknes
          path: build/app/outputs/flutter-apk/app-release.apk
